pipeline {
    agent any
    tools {
        maven 'MAVEN_DEF'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    // credentialsId: 'credentials',
                    url: 'https://github.com/DouglasGo8/MMP-Camel-JenkinsGit.git'
            }
        }
        stage('build') {
            steps {
                sh 'mvn -DskipTests compile'
            }
        }
        stage('unit-test') {
            steps {
                sh 'mvn compile camel:run'
            }
        }
        stage ('docker build') {
            steps {
                sh 'docker build -t app .'
            }
        }
        stage ('docker push') {
            steps {
                sh 'docker push douglasdb/app:latest'
            }
        }
    }
}