pipeline {
    // directives
    agent any
    triggers { cron ('* * * * *') } // Execute automatically every minute
    options { timeout (time: 5) } // stop the execution over 5 minutes
    parameters {
        booleanParam(name: 'DEBUG_BUILD', defaultValue: true, 
            description: 'Is it the debug build?')
    }
    // sections
    stages {
        stage('sample') {
            environment {NAME = 'Douglas db'}
            when { expression { return params.DEBUG_BUILD }}
            steps {
                echo "Hello from $NAME"
                script {
                    def browsers = ['chrome', 'firefox']
                    for (int i=0;i< browsers.size(); i++) {
                        echo "Testing the ${browsers[i]} browser."
                    }
                }
            }
        }
    }
    post { always { echo 'I will always say Hello again!'}}
}